---
title: "02 Data Acqusition"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```


# Bike types and prices



The following table shows the bikenames and prices 

```{r}
library(jsonlite)
library(tidyverse)
library(xml2)
library(httr)
library(rvest)  
url  <- "https://www.radon-bikes.de/e-bike/mountainbike/bikegrid/"
html <- url %>% 
  read_html()
rank <-  html %>% 
  html_nodes(css = ".small-12 .a-heading--small")%>% 
  html_text()
  rank_non<-stringr::str_replace(rank, "\n", "")  %>%   #remove /n
  discard(.p = ~stringr::str_detect(.x,"Welcome to our Radon-Bikes Instagram!|#radonbikes #bisbaldimwald"))
  rank_non2<-stringr::str_extract(rank_non,"(?<= ).*(?=\n)")

  ##price of each bike type 
  bikeprice<-  html %>% 
    html_nodes(css = ".small-12 .currency_eur .m-bikegrid__price--active") %>% 
    html_text()
  
  rank_non3<-stringr::str_extract(bikeprice,"[0-9]+")%>%
  as.numeric()
  
  #vector to table 
  

#fill the names to a table m-bikegrid__price--active
  imdtbl <- tibble(Bike_names=rank_non2,Bike_price=rank_non3)
  imdtbl
```