---
title: "04 Data Visualization"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

**IMPORTANT:** You can delete everything in here and start fresh. You might want to start by not deleting anything above this line until you know what that stuff is doing.



# Exercise 4 part 1

Last compiled: `r Sys.Date()`
Plotting covid data





```{r}

library(tidyverse)
covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
new_cov_table<-covid_data_tbl%>%select(continent,date,total_cases)%>%  group_by(continent,date) %>% summarize(total.cases = sum(total_cases)) %>%
    ungroup()


new_cov_table %>% group_by(continent,date)%>% 
    
    ggplot(aes(date,total.cases, fill = continent,color =continent)) +
    
    geom_line(size = 0.5, linetype = 1) +
    # facet_wrap(~ frame_material, ncol = 1) +
  
    theme(legend.position = "bottom")+geom_smooth(method = "loess", span = 0.2)+
  labs(
        title = "Covid cases in the 7 continents",
   
        fill = "continent" ,  
        x = "Date",
        y = "Total cases"

    )

```



